title: babyvector
name: babyvectorhomepage
description: hello
url: http://babyvector.github.io

# 自定义post url
permalink: /blog/:title.html
#timezone: Asia/Kaifeng

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false



#由于使用的是markdown pad为了适应kramdown语法在使用# header的时候要有空格且要空一行
highlighter:  rouge
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
      
encoding: utf-8

#hard_wrap: false
#  use_coderay: true
#syntax_highlighter: rouge
# coderay:
 # coderay_line_numbers:  nil

# White-listed plugins
#plugins:
 # - jekyll-sitemap
  
  
