title: babyvector
name: babyvectorhomepage
description: hello
url: http://babyvector.github.io

# 自定义post url
permalink: /blog/:title.html
#timezone: Asia/Kaifeng

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
#highlighter:  pygments

#kramdown:
#    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#    extensions:
#    - autolink
#    - footnotes
#    - smart
encoding: utf-8

#hard_wrap: false
#  use_coderay: true
#syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
plugins:
  - jekyll-sitemap
